### ISSUE TITLE
Code release of HDFormer?

### ISSUE THREAD

**Issue by kailu22** [JLDeng/SSCNN#1]
Thanks for the excellent work! Is this repo the code release of "The Bigger the Better? Rethinking the Effective Model Scale in Long-term Time Series Forecasting"? Much appreciated.

**Comment by JLDeng** [comment]
Thank you for your interest! A revised version of the mentioned paper has been accepted at NeurIPS 2024, and the code is now publicly available in this repository.

**Comment by JLDeng** [comment]
Thank you for your interest! A revised version of the mentioned paper has been accepted at NeurIPS 2024, and the code is now publicly available in this repository.
